[font]

normal = { family = "Fira Code", style = "Retina" }
bold = { family = "Fira Code", style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

size = 13
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true
