[mouse]
hide_when_typing = false

# Example of array of tables
# [[mouse.bindings]]
# mouse = "Right"
# action = "ExpandSelection"

# [[mouse.bindings]]
# mouse = "Right"
# mods = "Control"
# action = "ExpandSelection"

# Same representation
# bindings = [
#     { mouse = "Right", action = "ExpandSelection" },
#     { mouse = "Right", mods = "Control", action = "ExpandSelection" },
# ]
